development:
  adapter: sqlite3
  database: db/wytiwy_dev.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/wytiwy_dev.sqlite3
  pool: 5
  timeout: 5000


default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
