development:
  adapter: postgresql
  encoding: unicode
  database: mou
  pool: 5
  username: mou
  password: mou


test:
  adapter: sqlite3
  database: db/ideas_test.sqlite3
  pool: 5
  timeout: 5000

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
